# This is a config for E2B sandbox template.
# You can use template ID (cxpiezup3vm6dqmhe3jg) or template name (e2b-with-docker) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("e2b-with-docker") # Sync sandbox
# sandbox = await AsyncSandbox.create("e2b-with-docker") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('e2b-with-docker')

team_id = "460355b3-4f64-48f9-9a16-4442817f79f5"
dockerfile = "e2b.Dockerfile"
template_name = "e2b-with-docker"
template_id = "cxpiezup3vm6dqmhe3jg"
