# This is a config for E2B sandbox template.
# You can use template ID (yawhmlwp112j6igaydwp) or template name (openai-codex) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("openai-codex") # Sync sandbox
# sandbox = await AsyncSandbox.create("openai-codex") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('openai-codex')

team_id = "460355b3-4f64-48f9-9a16-4442817f79f5"
memory_mb = 4_096
cpu_count = 4
dockerfile = "e2b.Dockerfile"
template_name = "openai-codex"
template_id = "yawhmlwp112j6igaydwp"
