# This is a config for E2B sandbox template.
# You can use 'template_id' (p74qm9n4o5speg27n7ko) or 'template_name (react-template) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='react-template')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'react-template' })

template_id = "p74qm9n4o5speg27n7ko"
dockerfile = "e2b.Dockerfile"
template_name = "react-template"
start_cmd = "cd /home/user/my-app && npm start && sleep 60"
cpu_count = 8
memory_mb = 8_192
