# This is a config for E2B sandbox template.
# You can use 'template_id' (f9x6zoonta87xjstbft7) or 'template_name (code-interpreter-llama-index) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='code-interpreter-llama-index')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'code-interpreter-llama-index' })

dockerfile = "e2b.Dockerfile"
template_name = "code-interpreter-llama-index"
template_id = "f9x6zoonta87xjstbft7"
