# This is a config for E2B sandbox template.
# You can use 'template_id' (m5hqpa7aut6vrbpsl7su) or 'template_name (playwright-chromium) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='playwright-chromium')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'playwright-chromium' })

team_id = "460355b3-4f64-48f9-9a16-4442817f79f5"
dockerfile = "e2b.Dockerfile"
template_name = "playwright-chromium"
template_id = "m5hqpa7aut6vrbpsl7su"
